  deploy:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install AWS EB CLI and AWS CLI
          command: |
            pip install awsebcli awscli
      - run:
          name: Initialize Elastic Beanstalk
          command: |
            cd udagram/udagram-api
            eb init udagram-api --region $AWS_REGION --platform "Node.js 20 running on 64bit Amazon Linux 2023"
      - run:
          name: Set environment variables in Elastic Beanstalk
          command: |
            cd udagram/udagram-api
            eb setenv \
              AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
              AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
              AWS_REGION=$AWS_REGION \
              AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION \
              AWS_BUCKET=$AWS_BUCKET \
              POSTGRES_HOST=$POSTGRES_HOST \
              POSTGRES_DB=$POSTGRES_DB \
              POSTGRES_USER=$POSTGRES_USER \
              POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
              JWT_SECRET=$JWT_SECRET
      - run:
          name: Deploy API to Elastic Beanstalk
          command: |
            cd udagram/udagram-api
            eb deploy udagram-api
      - run:
          name: Deploy Frontend to S3
          command: |
            cd udagram/udagram-frontend
            aws s3 sync www s3://udagram-frontend-radu --delete
