version: 2.1

orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  build:
    docker:
      - image: cimg/node:14.15
    steps:
      - checkout
      - node/install:
          node-version: '14.15'
      - run:
          name: Install dependencies for frontend
          command: |
            cd udagram/udagram-frontend
            npm install
            npm install typescript@3.5.3 --save-dev
      - run:
          name: Install dependencies for backend
          command: |
            cd udagram/udagram-api
            npm install
      - run:
          name: Build frontend
          command: |
            cd udagram/udagram-frontend
            ./node_modules/.bin/ng build --prod
      - run:
          name: Build backend
          command: |
            cd udagram/udagram-api
            npm run build
      - persist_to_workspace:
          root: .
          paths:
            - udagram/udagram-frontend/www
            - udagram/udagram-api/www

  deploy:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install AWS EB CLI and AWS CLI
          command: |
            pip install awsebcli awscli
      - run:
          name: Initialize Elastic Beanstalk
          command: |
            cd udagram/udagram-api
            eb init udagram-api --region $AWS_REGION --platform "Node.js 14"
      - run:
          name: Set environment variables in Elastic Beanstalk
          command: |
            cd udagram/udagram-api
            eb setenv \
              AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
              AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
              AWS_REGION=$AWS_REGION \
              AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION \
              AWS_BUCKET=$AWS_BUCKET \
              POSTGRES_HOST=$POSTGRES_HOST \
              POSTGRES_DB=$POSTGRES_DB \
              POSTGRES_USER=$POSTGRES_USER \
              POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
              JWT_SECRET=$JWT_SECRET
      - run:
          name: Deploy API to Elastic Beanstalk
          command: |
            cd udagram/udagram-api
            eb deploy udagram-api
      - run:
          name: Deploy Frontend to S3
          command: |
            cd udagram/udagram-frontend
            aws s3 sync www s3://udagram-frontend-radu --delete

workflows:
  udagram:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
